apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a-db
  template:
    metadata:
      labels:
        app: service-a-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: auth-db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: service-a-db
spec:
  selector:
    app: service-a-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP